[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
boring_onchain_queue = "G1e7FfxiBovJMqmu5LtGvRsnAAzHHjYiaQdtpRyax1Y2"
boring_vault_svm = "ES38ztU5RYeoRheN24MJrJExrqzZYmtLz2dby7Es1Zxp"
endpoint = "G4JKZ4AZ6BcfFCZcitqhEoZdMDgTKzfHeBqd9RLqoJAq"
layer_zero_share_mover = "ETiijauRzxSQ2UdyiTzQKP4pH2vi8w4wanDfV1PKmHiy"
state_assert = "FJUvcmwAqdzdw4KhNjT7U7PZPi1o54HZaNYAXyNZ32eZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
receive_lz = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/receive_lz.ts"
send_lz = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/send_lz.ts"
test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
