[package]
name = "endpoint"
version = "0.1.0"
description = "A mock implementation of the LayerZero Endpoint program for local testing and development. Simulates message sending and receiving without actual cross-chain communication."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "endpoint"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("custom-heap", "custom-panic", "anchor-debug"))',
    'cfg(target_os, values("solana"))'
] }

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]


[dependencies]
anchor-lang = { workspace = true }
