[package]
name = "boring-vault-svm"
version = "0.1.0"
description = "Core implementation of the Boring Vault protocol on Solana. Manages asset deposits, share minting, yield strategy deployment, and exchange rate calculations using Oracle feeds (Switchboard/Pyth)."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "boring_vault_svm"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
rust_decimal = { workspace = true }
solana-program = { workspace = true }
hex = "0.4.3"
spl-token-metadata-interface = "0.7.0"
spl-type-length-value = "0.8.0"
pyth-solana-receiver-sdk = "1.1.0"
switchboard-on-demand = { version = "0.11.1", default-features = false, features = [
    "solana-v3",
    "cpi",
] }
